# Generated by Django 6.0.1 on 2026-06-10 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du service')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Code court (ex: REA, URG)')),
                ('building', models.CharField(max_length=50, verbose_name='Bâtiment / Aile')),
                ('floor', models.IntegerField(default=0, verbose_name='Étage')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Lit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, verbose_name='Numéro du lit (ex: CH-102-A)')),
                ('status', models.CharField(choices=[('DISPO', 'Disponible'), ('OCCUPE', 'Occupé'), ('NETTOYAGE', 'En cours de nettoyage'), ('RESERVE', 'Réservé / Bloqué')], default='DISPO', max_length=20, verbose_name='Statut actuel')),
                ('bed_type', models.CharField(choices=[('STANDARD', 'Lit Standard'), ('REA', 'Lit de Réanimation'), ('SI', 'Soins Intensifs')], default='STANDARD', max_length=20, verbose_name='Type de lit')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lits', to='hospital.service', verbose_name='Service associé')),
            ],
            options={
                'verbose_name': 'Lit',
                'verbose_name_plural': 'Lits',
                'unique_together': {('number', 'service')},
            },
        ),
    ]
