# Generated by Django 6.0.1 on 2026-06-10 01:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriqueLit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20, verbose_name='Ancien statut')),
                ('new_status', models.CharField(max_length=20, verbose_name='Nouveau statut')),
                ('date_action', models.DateTimeField(auto_now_add=True, verbose_name='Date du changement')),
                ('lit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiques', to='hospital.lit', verbose_name='Lit concerné')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Opérateur')),
            ],
            options={
                'verbose_name': 'Historique de lit',
                'verbose_name_plural': 'Historique des lits',
                'ordering': ['-date_action'],
            },
        ),
    ]
